WITH products AS (
    SELECT * FROM {{ ref('stg_products') }}
),
orders AS (
    SELECT * FROM {{ ref('int_orders_products') }}
),
events AS (
    SELECT * FROM {{ ref('stg_events') }}
)

SELECT  products.PRODUCT_GUID
        ,products.PRODUCT_NAME
        ,products.PRODUCT_PRICE
        ,IFNULL(products.PRODUCT_INVENTORY,0) AS CURRENT_PRODUCT_INVENTORY
        ,IFNULL(COUNT(DISTINCT orders.ORDER_GUID),0) AS DISTINCT_ORDERS
        ,IFNULL(SUM(orders.QUANTITY_ORDERED),0) AS QUANTITY_SOLD
        ,IFNULL(SUM(orders.PRODUCT_SUBTOTAL),0) AS PRODUCT_REVENUE
        ,COUNT(DISTINCT CASE WHEN events.EVENT_TYPE = 'PAGE_VIEW' THEN events.SESSION_GUID ELSE NULL END) AS PRODUCT_VIEWED_SESSIONS
        ,COUNT(DISTINCT CASE WHEN events.EVENT_TYPE = 'ADD_TO_CART' THEN events.SESSION_GUID ELSE NULL END) AS PRODUCT_ADDED_TO_CART_SESSIONS
        ,COUNT(DISTINCT orders.SESSION_GUID) AS PRODUCT_ORDERED_SESSIONS -- product order sessions
        ,PRODUCT_ORDERED_SESSIONS / PRODUCT_VIEWED_SESSIONS AS PRODUCT_CONVERSION_RATE
FROM products
LEFT JOIN orders ON products.PRODUCT_GUID = orders.PRODUCT_GUID
LEFT JOIN events ON products.PRODUCT_GUID = events.PRODUCT_GUID
GROUP BY    products.PRODUCT_GUID
            ,products.PRODUCT_NAME
            ,products.PRODUCT_PRICE
            ,CURRENT_PRODUCT_INVENTORY